#!/usr/bin/env python
import sys

if __name__ == "__main__":
    args = sys.argv[1:]
    s = " " + chr(int("1F97A", 16)) + " "
    if args:
        for i in range(int(args[0])):
            print(s, end = " ")
        print()
    else:
        print(s)
